### PR TITLE
Relay logging cleanup

### PR DESCRIPTION
**Pull request by felinira**
This does not really clean up the actual code but it adds env_logger and makes the logging output pretty.

For debugging use RUST_LOG=debug env var, the default log level is set to info.

### CODE REVIEW

**Comment by landhb** [comment]
@felinira would you be able to rebase this branch with the current master? Would be easier to review the changes etc. Since this branch currently also contains the commits from the #5 PR.

**Comment by felinira** [comment]
@landhb done

**Comment by landhb** [comment]
Perfect thanks!

**Comment by landhb** [comment]
@felinira I really like the `[{:.6}] ` tracing for each connection ID. Great idea

**Comment by landhb** [comment]
Merged @felinira. Thanks for the contribution! I'll roll this into the next release.

**Pull request merged**
